CICD: Make sure SB3's env checker recent enough
Otherwise conda may pick an old version that requires a gym.Env rather
than gymnasium.Env:

    Traceback (most recent call last):
      File "/home/runner/.cache/bazel/_bazel_runner/a5d028bd03bb4878c3b25e127027cdcf/sandbox/linux-sandbox/597/execroot/upkie/bazel-out/k8-fastbuild/bin/upkie/envs/wrappers/tests/differentiate_action_test.runfiles/upkie/upkie/envs/wrappers/tests/differentiate_action_test.py", line 40, in test_check_env
        check_env(diff_env)
      File "/home/runner/micromamba/envs/myenv/lib/python3.9/site-packages/stable_baselines3/common/env_checker.py", line 259, in check_env
        assert isinstance(
    AssertionError: Your environment must inherit from the gym.Env class cf https://github.com/openai/gym/blob/master/gym/core.py