docs: Version pin Doxygen to avoid undocumented-tuple error
The following error appears with more recent versions of Doxygen:

    upkie/upkie/controllers/joystick_gyropod_controller.py:148: error: documented symbol 'tuple' was not declared or defined. (warning treated as error, aborting now)

Its root cause is unclear to me, so I am version-pinning Doxygen for now.